-- CreateEnum
CREATE TYPE "MappingStatus" AS ENUM ('CONFIRMED', 'PENDING_REVIEW', 'CONFLICTED');

-- DropIndex
DROP INDEX "Product_clientId_nameStandard_key";

-- DropIndex
DROP INDEX "ProductMapping_clientId_chain_portalString_key";

-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "purchasePriceBase" DECIMAL(12,2),
ADD COLUMN     "salePriceBase" DECIMAL(12,2),
ADD COLUMN     "skuCode" TEXT NOT NULL;

-- AlterTable
ALTER TABLE "ProductMapping" ADD COLUMN     "status" "MappingStatus" NOT NULL DEFAULT 'CONFIRMED';

-- CreateTable
CREATE TABLE "ProductPriceOverride" (
    "id" TEXT NOT NULL,
    "productId" TEXT NOT NULL,
    "chain" "Chain" NOT NULL,
    "purchasePrice" DECIMAL(12,2),
    "salePrice" DECIMAL(12,2),
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ProductPriceOverride_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ThresholdConfig" (
    "id" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "criticoDays" INTEGER NOT NULL DEFAULT 7,
    "riesgoDays" INTEGER NOT NULL DEFAULT 14,
    "atencionDays" INTEGER NOT NULL DEFAULT 21,
    "excesoDays" INTEGER NOT NULL DEFAULT 60,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ThresholdConfig_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "ProductPriceOverride_productId_idx" ON "ProductPriceOverride"("productId");

-- CreateIndex
CREATE UNIQUE INDEX "ProductPriceOverride_productId_chain_key" ON "ProductPriceOverride"("productId", "chain");

-- CreateIndex
CREATE UNIQUE INDEX "ThresholdConfig_clientId_key" ON "ThresholdConfig"("clientId");

-- CreateIndex
CREATE UNIQUE INDEX "Product_clientId_skuCode_key" ON "Product"("clientId", "skuCode");

-- CreateIndex
CREATE INDEX "ProductMapping_clientId_chain_portalString_idx" ON "ProductMapping"("clientId", "chain", "portalString");

-- AddForeignKey
ALTER TABLE "ProductPriceOverride" ADD CONSTRAINT "ProductPriceOverride_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ThresholdConfig" ADD CONSTRAINT "ThresholdConfig_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Hand-edited (NOT generated by Prisma): partial unique index for ProductMapping.
-- Replaces the removed @@unique([clientId, chain, portalString]). CONFIRMED and
-- PENDING_REVIEW rows stay unique; CONFLICTED rows are exempt so N candidate SKUs
-- can claim the same portalString. See onetable-fase2-spec.md §4.4 / §8.
CREATE UNIQUE INDEX "ProductMapping_active_unique"
  ON "ProductMapping"("clientId", "chain", "portalString")
  WHERE "status" <> 'CONFLICTED';

